import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { connectToMongoDB } from "./lib/mongodb";
import Navbar from "./components/Navbar/navbar";
import { AppWrapper } from "./context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectToMongoDB();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>
          <div>
            <Navbar/>
            {children}
          </div>
        </AppWrapper>
      </body>
    </html>
  );
}
